ALTER TABLE institution ADD COLUMN IF NOT EXISTS rfc TEXT;
ALTER TABLE institution ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE institution ADD COLUMN IF NOT EXISTS state TEXT;
ALTER TABLE institution ADD COLUMN IF NOT EXISTS postal_code TEXT;
ALTER TABLE institution ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE institution ADD COLUMN IF NOT EXISTS website TEXT;
